apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ecommerce
  serviceName: ecommerce
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      # Include below storageClass in overlay if wanting to use local SSD.
      # storageClassName: "local-storage"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ecommerce
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      securityContext:
        runAsUser: 11111
        runAsGroup: 0
      containers:
      - name: ecommerce
        image: taggarwal175/ecommerce_lt1:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REACT_APP_HOST
          value: "localhost"
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 400Mi
            cpu: 250m
        volumeMounts:
        - name: ecommerce
          mountPath: /var/opt/ecommerce
      volumes:
      - name: ecommerce
        emptyDir: {}
