apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mssql-deployment
  serviceName: mssql
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      # Include below storageClass in overlay if wanting to use local SSD.
      # storageClassName: "local-storage"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mssql-deployment
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      containers:
      - name: mysql
        image: taggarwal175/mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 400Mi
            cpu: 250m
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        emptyDir: {}
