apiVersion: v1
kind: Service
# Note that the service name is still openam - not am. Need to change the config....
metadata:
  name: mssql
spec:
  ports:
  - name: mssql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/component: mssql
  type: ClusterIP
