apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api-gateway
  serviceName: api-gateway
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      # Include below storageClass in overlay if wanting to use local SSD.
      # storageClassName: "local-storage"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api-gateway
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      securityContext:
        runAsUser: 11111
        runAsGroup: 0
      containers:
      - name: api-gateway
        image: taggarwal175/api-gateway_lt1:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: API_HOST
          value: "localhost"
        - name: API_PORT
          value: "3000"
        - name: USER_HOST
          value: "10.244.0.8"
        - name: PRODUCT_HOST
          value: "localhost"
        - name: PRODUCT_PORT
          value: "3002"
        - name: PAYMENT_HOST
          value: "localhost"
        - name: PAYMENT_PORT
          value: "3003"
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 8443
          name: https 
        resources:
          limits:
            memory: 2000Mi
          requests:
            memory: 1800Mi
            cpu: 250m
        volumeMounts:
        - name: api-gateway
          mountPath: /var/opt/api
      volumes:
      - name: api-gateway
        emptyDir: {}
