apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: microservices
  serviceName: microservices
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      # Include below storageClass in overlay if wanting to use local SSD.
      # storageClassName: "local-storage"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/component: microservices
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      securityContext:
        runAsUser: 11111
        runAsGroup: 0
      containers:
      - name: microservices
        image: taggarwal175/microservices_lt:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DB_HOST
          value: "10.244.0.4"
        ports:
        - containerPort: 3000
          name: api-gateway
        - containerPort: 3011
          name: user-service
        - containerPort: 3012
          name: product-service
        - containerPort: 3013
          name: payment-service		  
        resources:
          limits:
            memory: 900Mi
          requests:
            memory: 800Mi
            cpu: 250m
        volumeMounts:
        - name: microservices
          mountPath: /var/opt/microservices
      volumes:
      - name: microservices
        emptyDir: {}
