apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: product-service
  serviceName: product-service
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      # Include below storageClass in overlay if wanting to use local SSD.
      # storageClassName: "local-storage"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/component: product-service
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      securityContext:
        runAsUser: 11111
        runAsGroup: 0
      containers:
      - name: product-service
        image: taggarwal175/product-service_lt:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DB_HOST
          value: "10.244.0.4"
        #- name: DB_PORT
        #  value: "3304"
        #- name: DB_PASSWORD
        #  value: "password"
        ports:
        - containerPort: 3002
          name: http
        - containerPort: 8443
          name: https 
        resources:
          limits:
            memory: 400Mi
          requests:
            memory: 300Mi
            cpu: 250m
        volumeMounts:
        - name: product-service
          mountPath: /var/opt/api
      volumes:
      - name: product-service
        emptyDir: {}
